I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script
    rey "Yo soy la reina Eileen"
Exception: Sayer 'rey' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 18, in script
    rey "Yo soy la reina Eileen"
  File "C:\Users\DrawH\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\DrawH\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'rey' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
Prueba1 1.0
Sat Feb 24 14:38:56 2024
